### ISSUE TITLE
run error in LSROloss(nn.Module):

### ISSUE THREAD

**Issue by SpiritBear000** [qiaoguan/Person-reid-GAN-pytorch#20]
when i run train_baseline.py

![2018-11-23 20-35-58](https://user-images.githubusercontent.com/32519071/48943963-d63c2e80-ef5f-11e8-85c4-8231e1c73b2e.png)

########## error log ############

Traceback (most recent call last):
  File "/Person-reid-GAN-pytorch/train_baseline.py", line 371, in <module>
    num_epochs=130)
  File "/Person-reid-GAN-pytorch/train_baseline.py", line 251, in train_model
    loss = criterion(outputs,labels,flags)
  File "/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/Person-reid-GAN-pytorch/train_baseline.py", line 178, in forward
    return loss.mean()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:339
/pytorch/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [0,0,0], thread: [10,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/pytorch/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [0,0,0], thread: [13,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.

**Comment by yangjunting100** [comment]
I think your pycharm 161 line. The function (torch.max) is wrong use. Because this want to return the "index of the biggest value" in each row, but this "  __， maxRow = torch.max(input.data, 1)" may be the right order. （the order of the result may be wrong.） I do not sure, but want to help you ,thanks.

**Comment by PratikKulkar** [comment]
Hey, did you got the solution I am also facing the same issue while training GAN!
